import InvoiceService from "../services/invoiceService.js";
import ItemService from "../services/itemService.js";
import CustomerService from "../services/customerService.js";
import TransactionService from "../services/transactionService.js";
import { generateInvoicePDF } from "../utils/invoiceGenerator.js";
import { sendEmail } from "../utils/emailService.js";
import { info, error } from "../utils/logger.js";

/**
 * @desc Create a new invoice (Billing)
 * @route POST /api/pos/invoice
 */
export const createInvoice = async (req, res) => {
  try {
    const { customerId, items, discount = 0, paidAmount = 0, paymentMethod } = req.body;

    if (!items || items.length === 0)
      return res.status(400).json({ message: "No items in invoice" });

    // Calculate totals
    let subtotal = 0;
    for (const it of items) subtotal += it.quantity * it.price;
    const totalAmount = subtotal - discount;

    // IMPORTANT: Walk-in customers cannot take due
    if (!customerId && paidAmount < totalAmount) {
      return res.status(400).json({ 
        message: "Walk-in customers must pay full amount. Please add customer details to allow credit." 
      });
    }

    // Verify all items belong to current user
    for (const it of items) {
      const item = await ItemService.findOne({ _id: it.item, addedBy: req.user._id });
      if (!item) {
        return res.status(400).json({ 
          message: `Item not found or unauthorized: ${it.item}` 
        });
      }
      
      // Check stock availability
      if (item.stockQty < it.quantity) {
        return res.status(400).json({ 
          message: `Insufficient stock for ${item.name}. Available: ${item.stockQty}` 
        });
      }
    }

    // Verify customer belongs to current user if provided
    if (customerId) {
      const customer = await CustomerService.findOne({ 
        _id: customerId, 
        owner: req.user._id 
      });
      if (!customer) {
        return res.status(400).json({ 
          message: "Customer not found or unauthorized" 
        });
      }
    }

    // Create invoice number (ex: INV-00001) - unique per user
    const count = await InvoiceService.countDocuments({ createdBy: req.user._id });
    const invoiceNo = `INV-${String(count + 1).padStart(5, "0")}`;

    // Save invoice
    const invoice = await InvoiceService.create({
      invoiceNo,
      customer: customerId || null,
      items,
      subtotal,
      discount,
      totalAmount,
      paidAmount,
      paymentMethod,
      paymentStatus:
        paidAmount >= totalAmount ? "paid" : paidAmount > 0 ? "partial" : "unpaid",
      createdBy: req.user._id,
    });

    // Update stock
    for (const it of items) {
      await ItemService.incrementField(it.item, "stockQty", -it.quantity);
    }

    // Handle customer dues if unpaid
    if (customerId && paidAmount < totalAmount) {
      const dueAmount = totalAmount - paidAmount;
      await CustomerService.incrementField(customerId, "dues", dueAmount);

      await TransactionService.create({
        type: "due",
        customer: customerId,
        invoice: invoice._id,
        amount: dueAmount,
        description: `Due added for invoice ${invoiceNo}`,
      });
    }

    // Record payment transaction
    if (paidAmount > 0) {
      await TransactionService.create({
        type: "payment",
        customer: customerId,
        invoice: invoice._id,
        amount: paidAmount,
        paymentMethod,
        description: `Payment received for invoice ${invoiceNo}`,
      });
    }

    // Generate invoice PDF + Email it + Log it
    let populatedInvoice = await InvoiceService.findById(invoice._id);
    populatedInvoice = await InvoiceService.populateCustomer(populatedInvoice);
    const pdfPath = await generateInvoicePDF(populatedInvoice);

    if (populatedInvoice.customer?.email) {
      await sendEmail(
        populatedInvoice.customer.email,
        `Invoice ${invoiceNo}`,
        `Thank you for your purchase! Attached is your invoice ${invoiceNo}.`,
        pdfPath
      );
    }

    info(`Invoice generated by ${req.user.name}: ${invoiceNo}`);

    res.status(201).json({ message: "Invoice created successfully", invoice: populatedInvoice });
  } catch (err) {
    error(`Invoice creation failed: ${err.message}`);
    res.status(500).json({ message: "Server Error", error: err.message });
  }
};

/**
 * @desc Get all invoices (only for current owner)
 * @route GET /api/pos/invoices
 */
export const getAllInvoices = async (req, res) => {
  try {
    let invoices = await InvoiceService.find({ createdBy: req.user._id, sort: "-createdAt" });
    
    // Populate customer field with selected fields
    invoices = await Promise.all(
      invoices.map(inv => InvoiceService.populateCustomerWithSelect(inv, ["name", "phone"]))
    );
    
    res.status(200).json(invoices);
  } catch (error) {
    res.status(500).json({ message: "Server Error", error: error.message });
  }
};

/**
 * @desc Get single invoice
 * @route GET /api/pos/invoice/:id
 */
export const getInvoiceById = async (req, res) => {
  try {
    let invoice = await InvoiceService.findOne({ 
      _id: req.params.id, 
      createdBy: req.user._id 
    });
    
    if (!invoice) {
      return res.status(404).json({ message: "Invoice not found or unauthorized" });
    }
    
    invoice = await InvoiceService.populateCustomer(invoice);
    res.status(200).json(invoice);
  } catch (error) {
    res.status(500).json({ message: "Server Error", error: error.message });
  }
};

/**
 * @desc Delete invoice
 * @route DELETE /api/pos/invoice/:id
 */
export const deleteInvoice = async (req, res) => {
  try {
    const invoice = await InvoiceService.findOne({ 
      _id: req.params.id, 
      createdBy: req.user._id 
    });
    
    if (!invoice) {
      return res.status(404).json({ message: "Invoice not found or unauthorized" });
    }

    await InvoiceService.deleteOne({ _id: req.params.id, createdBy: req.user._id });
    res.status(200).json({ message: "Invoice deleted" });
  } catch (error) {
    res.status(500).json({ message: "Server Error", error: error.message });
  }
};